name: Redeploy

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA'
        required: true

jobs:
  deploy:
    runs-on: self-hosted

    if: github.event_name == 'workflow_dispatch' && github.event.inputs.commit_sha != ''

    env:
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }} 
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }} 
      DATABASE_URL: ${{ secrets.DATABASE_URL }} 
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      MIN_PARTICIPANTS_DEFAULT: ${{ vars.MIN_PARTICIPANTS_DEFAULT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: export env
        run: |
          ENV_FILE=.env
          echo "" > $ENV_FILE

          echo "POSTGRES_DB=$POSTGRES_DB" >> $ENV_FILE
          echo "POSTGRES_USER=$POSTGRES_USER" >> $ENV_FILE
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> $ENV_FILE
          echo "DATABASE_URL=$DATABASE_URL" >> $ENV_FILE
          echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" >> $ENV_FILE
          echo "MIN_PARTICIPANTS_DEFAULT=$MIN_PARTICIPANTS_DEFAULT" >> $ENV_FILE

      - name: Build Docker image
        run: |
          docker compose --env-file .env -f docker-compose.yaml build
          docker compose --env-file .env -f docker-compose.yaml up -d --no-deps --force-recreate
